trackList = 
[ 
    {'title':"【Ado】逆光.mp3", 'file':"music/【Ado】逆光.mp3"},
    {'title':"【Creepy Nuts】 堕天.mp3", 'file':"music/【Creepy Nuts】 堕天.mp3"},
    {'title':"【ALI】LOST IN PARADISE.mp3", 'file':"music/【ALI】LOST IN PARADISE.mp3"},
    {'title':"【優里】ドライフラワー.mp3", 'file':"music/【優里】ドライフラワー.mp3"},
    {'title':"【米津玄師】 KICKBACK.mp3", 'file':"music/【米津玄師】 KICKBACK.mp3"},
    {'title':"【Nobodyknows】ココロオドル.mp3", 'file':"music/【Nobodyknows】ココロオドル.mp3"},
    {'title':"【THE ORAL CIGARETTES】狂乱 Hey Kids.mp3", 'file':"music/【THE ORAL CIGARETTES】狂乱 Hey Kids.mp3"},
    {'title':"【YOASOBI】三原色.mp3", 'file':"music/【YOASOBI】三原色.mp3"},
    {'title':"【Aimer】残響散歌.mp3", 'file':"music/【Aimer】残響散歌.mp3"},
    {'title':"【キタニタツヤ】 Rapport.mp3", 'file':"music/【キタニタツヤ】 Rapport.mp3"},
    {'title':"【King Gnu】 一途.mp3", 'file':"music/【King Gnu】 一途.mp3"},
    {'title':"【SEKAI NO OWARI】Habit.mp3", 'file':"music/【SEKAI NO OWARI】Habit.mp3"},
    {'title':"【ROSA WALTON & HALLIE COGGINS】 I REALLY WANT TO STAY AT YOUR HOUSE.mp3", 'file':"music/【ROSA WALTON & HALLIE COGGINS】 I REALLY WANT TO STAY AT YOUR HOUSE.mp3"},
    {'title':"【宇多田ヒカル】One Last Kiss.mp3", 'file':"music/【宇多田ヒカル】One Last Kiss.mp3"},
    {'title':"【yui】Again.mp3", 'file':"music/【yui】Again.mp3"},
    {'title':"【須田景凪】veil.mp3", 'file':"music/【須田景凪】veil.mp3"},
    {'title':"【Creepy Nuts】 よふかしのうた.mp3", 'file':"music/【Creepy Nuts】 よふかしのうた.mp3"},
    {'title':"【Eve】いのちの食べ方.mp3", 'file':"music/【Eve】いのちの食べ方.mp3"},
    {'title':"【魔界ノりりむ × 星川サラ】だいしきゅーだいしゅき.mp3", 'file':"music/【魔界ノりりむ × 星川サラ】だいしきゅーだいしゅき.mp3"},
    {'title':"【結束バンド】「ギターと孤独と蒼い惑星」.mp3", 'file':"music/【結束バンド】「ギターと孤独と蒼い惑星」.mp3"},
  ];
