trackList = 
[ 
{"icon":"cover/【yama】色彩.png", "title":"【yama】色彩.mp3", "file":"music/【yama】色彩.mp3"},
{"icon":"cover/【Ado】逆光.png", "title":"【Ado】逆光.mp3", "file":"music/【Ado】逆光.mp3"},
{"icon":"cover/【Creepy Nuts】 堕天.png", "title":"【Creepy Nuts】 堕天.mp3", "file":"music/【Creepy Nuts】 堕天.mp3"},
{"icon":"cover/【ALI】LOST IN PARADISE.png", "title":"【ALI】LOST IN PARADISE.mp3", "file":"music/【ALI】LOST IN PARADISE.mp3"},
{"icon":"cover/【優里】ドライフラワー.png", "title":"【優里】ドライフラワー.mp3", "file":"music/【優里】ドライフラワー.mp3"},
{"icon":"cover/【米津玄師】 KICKBACK.png", "title":"【米津玄師】 KICKBACK.mp3", "file":"music/【米津玄師】 KICKBACK.mp3"},
{"icon":"cover/【Nobodyknows】ココロオドル.png", "title":"【Nobodyknows】ココロオドル.mp3", "file":"music/【Nobodyknows】ココロオドル.mp3"},
{"icon":"cover/【THE ORAL CIGARETTES】狂乱 Hey Kids.png", "title":"【THE ORAL CIGARETTES】狂乱 Hey Kids.mp3", "file":"music/【THE ORAL CIGARETTES】狂乱 Hey Kids.mp3"},
{"icon":"cover/【YOASOBI】三原色.png", "title":"【YOASOBI】三原色.mp3", "file":"music/【YOASOBI】三原色.mp3"},
{"icon":"cover/【Aimer】残響散歌.png", "title":"【Aimer】残響散歌.mp3", "file":"music/【Aimer】残響散歌.mp3"},
{"icon":"cover/【Creepy Nuts  】のびしろ.png", "title":"【Creepy Nuts  】のびしろ.mp3", "file":"music/【Creepy Nuts  】のびしろ.mp3"},
{"icon":"cover/【キタニタツヤ】 Rapport.png", "title":"【キタニタツヤ】 Rapport.mp3", "file":"music/【キタニタツヤ】 Rapport.mp3"},
{"icon":"cover/【北村匠海】貓.png", "title":"【北村匠海】貓.mp3", "file":"music/【北村匠海】貓.mp3"},
{"icon":"cover/【YOASOBI】怪物.png", "title":"【YOASOBI】怪物.mp3", "file":"music/【YOASOBI】怪物.mp3"},
{"icon":"cover/【King Gnu】 一途.png", "title":"【King Gnu】 一途.mp3", "file":"music/【King Gnu】 一途.mp3"},
{"icon":"cover/【SEKAI NO OWARI】Habit.png", "title":"【SEKAI NO OWARI】Habit.mp3", "file":"music/【SEKAI NO OWARI】Habit.mp3"},
{"icon":"cover/【ROSA WALTON & HALLIE COGGINS】 I REALLY WANT TO STAY AT YOUR HOUSE.png", "title":"【ROSA WALTON & HALLIE COGGINS】 I REALLY WANT TO STAY AT YOUR HOUSE.mp3", "file":"music/【ROSA WALTON & HALLIE COGGINS】 I REALLY WANT TO STAY AT YOUR HOUSE.mp3"},
{"icon":"cover/【sayuri】Tower of Flower.png", "title":"【sayuri】Tower of Flower.mp3", "file":"music/【sayuri】Tower of Flower.mp3"},
{"icon":"cover/【宇多田ヒカル】One Last Kiss.png", "title":"【宇多田ヒカル】One Last Kiss.mp3", "file":"music/【宇多田ヒカル】One Last Kiss.mp3"},
{"icon":"cover/【神山羊】色香水.png", "title":"【神山羊】色香水.mp3", "file":"music/【神山羊】色香水.mp3"},
{"icon":"cover/【yui】Again.png", "title":"【yui】Again.mp3", "file":"music/【yui】Again.mp3"},
{"icon":"cover/【須田景凪】veil.png", "title":"【須田景凪】veil.mp3", "file":"music/【須田景凪】veil.mp3"},
{"icon":"cover/【Creepy Nuts】 よふかしのうた.png", "title":"【Creepy Nuts】 よふかしのうた.mp3", "file":"music/【Creepy Nuts】 よふかしのうた.mp3"},
{"icon":"cover/【Eve】いのちの食べ方.png", "title":"【Eve】いのちの食べ方.mp3", "file":"music/【Eve】いのちの食べ方.mp3"},
{"icon":"cover/【魔界ノりりむ × 星川サラ】だいしきゅーだいしゅき.png", "title":"【魔界ノりりむ × 星川サラ】だいしきゅーだいしゅき.mp3", "file":"music/【魔界ノりりむ × 星川サラ】だいしきゅーだいしゅき.mp3"},
{"icon":"cover/【結束バンド】「ギターと孤独と蒼い惑星」.png", "title":"【結束バンド】「ギターと孤独と蒼い惑星」.mp3", "file":"music/【結束バンド】「ギターと孤独と蒼い惑星」.mp3"}
]; 
