trackList = 
[ 
{name:"【Ado】逆光.mp3", src:"music/【Ado】逆光.mp3"},
{name:"【Creepy Nuts】 堕天.mp3", src:"music/【Creepy Nuts】 堕天.mp3"},
{name:"【ALI】LOST IN PARADISE.mp3", src:"music/【ALI】LOST IN PARADISE.mp3"},
{name:"【優里】ドライフラワー.mp3", src:"music/【優里】ドライフラワー.mp3"},
{name:"【米津玄師】 KICKBACK.mp3", src:"music/【米津玄師】 KICKBACK.mp3"},
{name:"【Nobodyknows】ココロオドル.mp3", src:"music/【Nobodyknows】ココロオドル.mp3"},
{name:"【THE ORAL CIGARETTES】狂乱 Hey Kids.mp3", src:"music/【THE ORAL CIGARETTES】狂乱 Hey Kids.mp3"},
{name:"【YOASOBI】三原色.mp3", src:"music/【YOASOBI】三原色.mp3"},
{name:"【THE ORAL CIGARETTES】狂乱 Hey Kids.mp3:Zone.Identifier", src:"music/【THE ORAL CIGARETTES】狂乱 Hey Kids.mp3:Zone.Identifier"},
{name:"【Aimer】残響散歌.mp3", src:"music/【Aimer】残響散歌.mp3"},
{name:"【須田景凪】veil.mp3:Zone.Identifier", src:"music/【須田景凪】veil.mp3:Zone.Identifier"},
{name:"【キタニタツヤ】 Rapport.mp3", src:"music/【キタニタツヤ】 Rapport.mp3"},
{name:"【Nobodyknows】ココロオドル.mp3:Zone.Identifier", src:"music/【Nobodyknows】ココロオドル.mp3:Zone.Identifier"},
{name:"【King Gnu】 一途.mp3", src:"music/【King Gnu】 一途.mp3"},
{name:"【yui】Again.mp3:Zone.Identifier", src:"music/【yui】Again.mp3:Zone.Identifier"},
{name:"【SEKAI NO OWARI】Habit.mp3", src:"music/【SEKAI NO OWARI】Habit.mp3"},
{name:"【ROSA WALTON & HALLIE COGGINS】 I REALLY WANT TO STAY AT YOUR HOUSE.mp3", src:"music/【ROSA WALTON & HALLIE COGGINS】 I REALLY WANT TO STAY AT YOUR HOUSE.mp3"},
{name:"【宇多田ヒカル】One Last Kiss.mp3:Zone.Identifier", src:"music/【宇多田ヒカル】One Last Kiss.mp3:Zone.Identifier"},
{name:"【Creepy Nuts】 堕天.mp3:Zone.Identifier", src:"music/【Creepy Nuts】 堕天.mp3:Zone.Identifier"},
{name:"【宇多田ヒカル】One Last Kiss.mp3", src:"music/【宇多田ヒカル】One Last Kiss.mp3"},
{name:"【yui】Again.mp3", src:"music/【yui】Again.mp3"},
{name:"【須田景凪】veil.mp3", src:"music/【須田景凪】veil.mp3"},
{name:"【Creepy Nuts】 よふかしのうた.mp3", src:"music/【Creepy Nuts】 よふかしのうた.mp3"},
{name:"【Eve】いのちの食べ方.mp3", src:"music/【Eve】いのちの食べ方.mp3"},
{name:"【魔界ノりりむ × 星川サラ】だいしきゅーだいしゅき.mp3", src:"music/【魔界ノりりむ × 星川サラ】だいしきゅーだいしゅき.mp3"},
{name:"【米津玄師】 KICKBACK.mp3:Zone.Identifier", src:"music/【米津玄師】 KICKBACK.mp3:Zone.Identifier"},
{name:"【結束バンド】「ギターと孤独と蒼い惑星」.mp3", src:"music/【結束バンド】「ギターと孤独と蒼い惑星」.mp3"},
{name:"【キタニタツヤ】 Rapport.mp3:Zone.Identifier", src:"music/【キタニタツヤ】 Rapport.mp3:Zone.Identifier"}
]; 
